<?php
/**
 * Created by PhpStorm.
 * User: leshu
 * Date: 2019/4/25
 * Time: 17:19
 */
namespace App\Controllers;
use CodeIgniter\Controller;
use App\Models\AdminModel;
use CodeIgniter\API\ResponseTrait;

use Config\Autoload;
use Config\App;
use Config\Cache;
use CodeIgniter\Cache\CacheFactory;
use CodeIgniter\Cache\CacheInterface;
use CodeIgniter\Config\Services;
use Config\Database;


class Ajax extends Controller {
    use ResponseTrait;

    //--------------------------------------------------------------------


    /**
     * -----------------------------------
     * @Date             2019-04-28
     * @Author           Acclea
     * @Describe         redis
     * -----------------------------------
     */
    public static $redisConn = '';

    //--------------------------------------------------------------------


    /**
     * -----------------------------------
     * @Date             2019-04-28
     * @Author           Acclea
     * @Describe         $sessionClass
     * -----------------------------------
     */
    public static $sessionClass = '';

    //--------------------------------------------------------------------


    /**
     * -----------------------------------
     * @Function        init
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         初始化
     * -----------------------------------
     */
    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger){
        parent::initController($request, $response, $logger);
        // TODO: Change the autogenerated stub


        // 加载redis
        if(empty(self::$redisConn)){
            $redisFact          = new CacheFactory();
            $config             = new Cache();
            self::$redisConn    = $redisFact->getHandler($config);
        }

        // 加载session
        if(empty(self::$sessionClass)){
            $services           = new Services();
//            $sessionConn        = $services->session();
            self::$sessionClass         = $services->session();
            self::$sessionClass->start();
        }

//        d(self::$sessionClass);die;

    }

    //--------------------------------------------------------------------


    /**
     * -----------------------------------
     * @Function        loginDo
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         异步登陆请求
     * @Param            name   用户名
     * @Param            pass   密码
     * -----------------------------------
     */
    public function loginDo(){

        //获取通过get提交的数据，
//        $getData   = $this->request->getGet();

        //获取通过post提交的数据，
        $postData   = $this->request->getPost();
        if(!isset($postData['name']) OR !isset($postData['pass'])){
            $refArr     = array(
                'code'  => -3,
                'msg'   => "非法请求",
            );
            die(json_encode($refArr,JSON_UNESCAPED_UNICODE));
        }

        $name   = $postData['name'];
        $pass   = $postData['pass'];

        if(!$name OR !$pass){
            $refArr     = array(
                'code'  => -4,
                'msg'   => "用户和密码不能为空",
            );
            die(json_encode($refArr,JSON_UNESCAPED_UNICODE));
        }

        //如果5min内密码连续输入错误5次，则10min内不允许登陆
        $cacheKeyAdminBan   = "ci4_test_admin_ban.".md5($name);
        $isBan      = self::$redisConn->get($cacheKeyAdminBan);
        if($isBan){
            $refArr     = array(
                'code'  => -5,
                'msg'   => "该用户已禁止登陆，请10分钟后尝试",
            );
            die(json_encode($refArr,JSON_UNESCAPED_UNICODE));
        }

        //从数据库读取数据,test789
        $adminModel = new AdminModel();
        $adminRow  = $adminModel->adminRow("name = '".$name."'","id,name,status,pass");

        if(!$adminRow){
            $refArr     = array(
                'code'  => -6,
                'msg'   => "用户不存在",
            );
            die(json_encode($refArr,JSON_UNESCAPED_UNICODE));
        }

        //验证密码
        if(sha1(md5($pass)) != $adminRow['pass']){
            $cacheKeyAdminPass  = "ci4_test_admin_pass.".md5($name);
            $isWrongPass    = self::$redisConn->get($cacheKeyAdminPass);
            if(!$isWrongPass){$isWrongPass = 0;}
            $isWrongPass++;

            if($isWrongPass == 5){
                $cacheKeyAdminBanExp    = 10*60;
                self::$redisConn->save($cacheKeyAdminBan,$name,$cacheKeyAdminBanExp);
                $refArr     = array(
                    'code'  => -5,
                    'msg'   => "该用户已禁止登陆，请10分钟后尝试",
                );
                die(json_encode($refArr,JSON_UNESCAPED_UNICODE));
            }

            $cacheKeyAdminPassExp    = 5*60;
            self::$redisConn->save($cacheKeyAdminPass,$isWrongPass,$cacheKeyAdminPassExp);
            $refArr     = array(
                'code'  => -7,
                'msg'   => "密码错误，请重新输入",
            );
            die(json_encode($refArr,JSON_UNESCAPED_UNICODE));
        }

        //密码正确，修改登陆时间，记录相关日志

        $refArr     = array(
            'code'  => 0,
            'msg'   => "OK",
            'data'  =>  array(
                'url'   => site_url('Home/index'),
            ),
        );

        die(json_encode($refArr,JSON_UNESCAPED_UNICODE));

    }

    //--------------------------------------------------------------------
}