<?php
/**
 * Created by PhpStorm.
 * User: leshu
 * Date: 2019/4/25
 * Time: 17:19
 */

namespace App\Controllers;
use CodeIgniter\Controllers;


class Ajax extends BaseController {

    public $aliases = [
        'apiPrep' => [
            \App\Config\App::class,
        ]
    ];
    /**
     * -----------------------------------
     * @Function        init
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         初始化
     * -----------------------------------
     */
    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger){
        parent::initController($request, $response, $logger);
        // TODO: Change the autogenerated stub
    }


    /**
     * -----------------------------------
     * @Function        loginDo
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         异步登陆请求
     * @Param            name   用户名
     * @Param            pass   密码
     * -----------------------------------
     */
    public function loginDo(){
        if(!$_POST){
            $refArr     = array(
                'code'  => -3,
                'msg'   => "非法请求",
            );
            echo json_encode($refArr,JSON_UNESCAPED_UNICODE);
        }

        $refArr     = array(
            'code'  => 0,
            'msg'   => "OK",
            'data'  =>  array(
                'url'   => site_url('Home/index'),
            ),
        );

        echo json_encode($refArr,JSON_UNESCAPED_UNICODE);

    }
}