<?php
namespace App\Controllers;

use CodeIgniter\Controllers;
use App\Models\AdminModel;

class Home extends BaseController{

    /**
     * -----------------------------------
     * @Function        init
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         初始化
     * -----------------------------------
     */
    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger){
        parent::initController($request, $response, $logger);
        // TODO: Change the autogenerated stub
    }

    //--------------------------------------------------------------------

    /**
     * -----------------------------------
     * @Function        index
     * @Date             2019-04-26
     * @Author           Acclea
     * @Describe         默认入口
     * -----------------------------------
     */
	public function index(){
        $ref    = array('templateTitle'=>"OA管理系统");
        return view('home/index',$ref);
	}

	//--------------------------------------------------------------------

}
