<?php
namespace App\Controllers;

use CodeIgniter\Controllers;
use App\Library;
use App\Models\AdminModel;


class Home extends BaseController{

    /**
     * -----------------------------------
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         加载系统需要的配置
     * -----------------------------------
     */


    /**
     * -----------------------------------
     * @Function        init
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         初始化
     * -----------------------------------
     */
    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger){
        parent::initController($request, $response, $logger);
        // TODO: Change the autogenerated stub

        //config array
//        self::$sysConf;
    }

    //--------------------------------------------------------------------

    /**
     * -----------------------------------
     * @Function        index
     * @Date             2019-04-26
     * @Author           Acclea
     * @Describe         默认入口
     * -----------------------------------
     */
	public function index(){
        $ref    = array();
        $ref['templateTitle']   = "OA管理系统";
        $ref['weblibUrl']       = self::$sysConf['app']->weblibURL;

        return view('home/index',$ref);
	}

	//--------------------------------------------------------------------

    /**
     * -----------------------------------
     * @Function        index
     * @Date             2019-04-26
     * @Author           Acclea
     * @Describe         默认入口
     * -----------------------------------
     */
	public function home(){
        $ref    = array('templateTitle'=>"OA管理系统");
        return view('home/home',$ref);
	}

	//--------------------------------------------------------------------

}
