<?php
/**
 * Created by PhpStorm.
 * User: leshu
 * Date: 2019/4/25
 * Time: 14:53
 */

namespace App\Controllers;
use CodeIgniter\Controller;
use CodeIgniter\Libraries;

class Login extends Controller{

    /**
     * -----------------------------------
     * @Function        init
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         初始化
     * -----------------------------------
     */
    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger){
        parent::initController($request, $response, $logger);
        // TODO: Change the autogenerated stub
    }

    //--------------------------------------------------------------------


    /**
     * -----------------------------------
     * @Function        index
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         默认入口
     * -----------------------------------
     */
    public function index(){
        $ref    = array('templateTitle'=>"登录");
        return view('login/index',$ref);
    }

    //--------------------------------------------------------------------


    /**
     * -----------------------------------
     * @Function        logout
     * @Date             2019-04-26
     * @Author           Acclea
     * @Describe         登出
     * -----------------------------------
     */
    public function logout(){
        $refArr     = array(
            'code'  => 0,
            'msg'   => "OK",
            'data'  =>  array(
                'url'   => site_url('Login/index'),
            ),
        );

        echo json_encode($refArr,JSON_UNESCAPED_UNICODE);
    }

    //--------------------------------------------------------------------
}