<?php
/**
 * Created by PhpStorm.
 * User: leshu
 * Date: 2019/4/25
 * Time: 14:53
 */

namespace App\Controllers;
use CodeIgniter\Controllers;
use App\Libraries;

class Login extends BaseController{

    /**
     * -----------------------------------
     * @Function        init
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         初始化
     * -----------------------------------
     */
    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger){
        parent::initController($request, $response, $logger);
        // TODO: Change the autogenerated stub
    }

    /**
     * -----------------------------------
     * @Function        index
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         默认入口
     * -----------------------------------
     */
    public function index(){
        return view('login/index');
    }


}