<?php
/**
 * Created by PhpStorm.
 * User: leshu
 * Date: 2019/4/26
 * Time: 10:43
 */

namespace App\Controllers;

use CodeIgniter\Config\App;
use App\Controllers;
use CodeIgniter\App\Libraries;
use App\Models\OfficeModel;

class Office extends BaseController {

    /**
     * -----------------------------------
     * @Function        init
     * @Date             2019-04-26
     * @Author           Acclea
     * @Describe         初始化
     * -----------------------------------
     */
    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger){
        parent::initController($request, $response, $logger);
        // TODO: Change the autogenerated stub
    }

    //--------------------------------------------------------------------

    /**
     * -----------------------------------
     * @Function        index
     * @Date             2019-04-26
     * @Author           Acclea
     * @Describe         默认入口
     * -----------------------------------
     */
    public function index(){
        SelfFunc::p($this);
        $ref    = array('templateTitle'=>"工作日志");
        return view('office/index',$ref);
    }

    //--------------------------------------------------------------------
}