<?php
/**
 * Created by PhpStorm.
 * User: leshu
 * Date: 2019/4/25
 * Time: 16:42
 * Describe : 自定义方法
 */

namespace App\Libraries;

use CodeIgniter\API\ResponseTrait;

class SelfFunc{
    use ResponseTrait;


    /**
     * -----------------------------------
     * @Function        init
     * @Date             2019-04-25
     * @Author           Acclea
     * @Describe         初始化
     * -----------------------------------
     */
    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger){
        parent::initController($request, $response, $logger);
        // TODO: Change the autogenerated stub

    }

    //--------------------------------------------------------------------


    /**
     * -----------------------------------
     * @Function            console
     * @describe            php封装JS->console --debug
     * @Date                2019-04-26
     * @Author              Acclea
     * @Param    string|array    $data   需要打印的内容
     * -----------------------------------
     */
    function console(string $data) {
        if (is_array($data) || is_object($data)) {
            echo("<script>console.log('".json_encode($data)."');</script>");
        } else {
            echo("<script>console.log('".$data."');</script>");
        }
    }

    //--------------------------------------------------------------------


    /**
     * -----------------------------------
     * @Function            p
     * @describe            php封装格式化print_r---debug
     * @Date                2019-04-26
     * @Author              Acclea
     * @Param    string|array    $data   需要打印的内容
     * -----------------------------------
     */
    function p(string $data){
        echo '<pre>';
        print_r($data);
        echo '</pre>';
    }

    //--------------------------------------------------------------------


    /**
     * -----------------------------------
     * @Function            refJson
     * @describe            返回客户端的数据格式，支持AJAX-JSONP、AJAX
     * @Date                2019-04-29
     * @Author              Acclea
     * @Param    int        $code   状态值
     * @Param    string     $msg    提示信息
     * @Param    array      $data   返回数据
     * -----------------------------------
     */
    function refJson(int $code = 0, string $msg = "OK", array $data = array()){

        $refArr     = array(
            'code'  => $code,
            'msg'   => $msg,
        );

        if($data){$refArr['data'] = $data;}

        $jsonStr    = json_encode($refArr,JSON_UNESCAPED_UNICODE);
/*
 *      // TODO ===暂时不清楚此处无法使用$request的原因=============
        //获取通过get提交的数据，
        $getData   = $this->request->getGet();
        if(isset($getData['callback'])){
            die($getData['callback'] .'('. $jsonStr .')');
        }elseif (isset($getData['jsoncallback'])){
            die($getData['jsoncallback'] .'('. $jsonStr .')');
        }


        //获取通过post提交的数据，
        $postData   = $this->request->getPost();
        if(isset($postData['callback'])){
            die($postData['callback'] .'('. $jsonStr .')');
        }elseif (isset($postData['jsoncallback'])){
            die($postData['jsoncallback'] .'('. $jsonStr .')');
        }
*/

        die($jsonStr);
    }

    //--------------------------------------------------------------------
}

